export const prismaErrorsCodes = [
  { code: "P1000", message: "Authentication failed against database server. Invalid credentials." },
  { code: "P1001", message: "Can't reach database server." },
  { code: "P1002", message: "Database server reached but timed out." },
  { code: "P1003", message: "Database does not exist." },
  { code: "P1008", message: "Operations timed out." },
  { code: "P1009", message: "Database already exists." },
  { code: "P1010", message: "User denied access to database." },
  { code: "P1011", message: "Error opening TLS connection." },
  { code: "P1012", message: "Schema validation/parsing error." },
  { code: "P1013", message: "Invalid database connection string." },
  { code: "P1014", message: "Underlying model/table does not exist." },
  { code: "P1015", message: "Database version not supported." },
  { code: "P1016", message: "Incorrect number of query parameters." },
  { code: "P1017", message: "Server closed the connection." },

  { code: "P2000", message: "Value too long for column type." },
  { code: "P2001", message: "Record does not exist." },
  { code: "P2002", message: "Unique constraint failed." },
  { code: "P2003", message: "Foreign key constraint failed." },
  { code: "P2004", message: "Database constraint failed." },
  { code: "P2005", message: "Invalid stored value for field type." },
  { code: "P2006", message: "Invalid value provided for field." },
  { code: "P2007", message: "Data validation error." },
  { code: "P2008", message: "Query parsing error." },
  { code: "P2009", message: "Query validation error." },
  { code: "P2010", message: "Raw query failed." },
  { code: "P2011", message: "Null constraint violation." },
  { code: "P2012", message: "Missing required value." },
  { code: "P2013", message: "Missing required argument." },
  { code: "P2014", message: "Relation violation error." },
  { code: "P2015", message: "Related record not found." },
  { code: "P2016", message: "Query interpretation error." },
  { code: "P2017", message: "Records not connected." },
  { code: "P2018", message: "Required connected records not found." },
  { code: "P2019", message: "Input error." },
  { code: "P2020", message: "Value out of range." },
  { code: "P2021", message: "Table does not exist." },
  { code: "P2022", message: "Column does not exist." },
  { code: "P2023", message: "Inconsistent column data." },
  { code: "P2024", message: "Connection pool timeout." },
  { code: "P2025", message: "Required records not found." },
  { code: "P2026", message: "Feature not supported by database." },
  { code: "P2027", message: "Multiple database errors occurred." },
  { code: "P2028", message: "Transaction API error." },
  { code: "P2029", message: "Query parameter limit exceeded." },
  { code: "P2030", message: "Missing full-text index." },
  { code: "P2031", message: "MongoDB requires replica set." },
  { code: "P2033", message: "Number exceeds 64-bit limit." },
  { code: "P2034", message: "Transaction conflict/deadlock." },
  { code: "P2035", message: "Database assertion violation." },
  { code: "P2036", message: "External connector error." },
  { code: "P2037", message: "Too many database connections." },

  { code: "P3000", message: "Failed to create database." },
  { code: "P3001", message: "Migration may cause data loss." },
  { code: "P3002", message: "Migration rolled back." },
  { code: "P3003", message: "Migration format changed." },
  { code: "P3004", message: "System database cannot be modified." },
  { code: "P3005", message: "Database schema not empty." },
  { code: "P3006", message: "Migration failed on shadow DB." },
  { code: "P3007", message: "Preview features not allowed." },
  { code: "P3008", message: "Migration already applied." },
  { code: "P3009", message: "Failed migrations exist." },
  { code: "P3010", message: "Migration name too long." },
  { code: "P3011", message: "Migration not applied." },
  { code: "P3012", message: "Migration not in failed state." },
  { code: "P3013", message: "Multiple providers not supported." },
  { code: "P3014", message: "Failed to create shadow database." },
  { code: "P3015", message: "Migration file not found." },
  { code: "P3016", message: "Database reset failed." },
  { code: "P3017", message: "Migration not found." },
  { code: "P3018", message: "Migration failed to apply." },
  { code: "P3019", message: "Provider mismatch." },
  { code: "P3020", message: "Shadow DB required (Azure SQL)." },
  { code: "P3021", message: "Foreign keys not supported." },
  { code: "P3022", message: "DDL execution disabled." },
  { code: "P3023", message: "Invalid external table identifier." },
  { code: "P3024", message: "Invalid simple identifier." },

  { code: "P4000", message: "Introspection failed." },
  { code: "P4001", message: "Database is empty." },
  { code: "P4002", message: "Database schema inconsistent." },

  { code: "P6000", message: "Generic server error." },
  { code: "P6001", message: "Invalid datasource URL." },
  { code: "P6002", message: "Unauthorized API key." },
  { code: "P6003", message: "Plan limit reached." },
  { code: "P6004", message: "Query timeout." },
  { code: "P6005", message: "Invalid parameters." },
  { code: "P6006", message: "Version not supported." },
  { code: "P6008", message: "Connection/engine start error." },
  { code: "P6009", message: "Response size limit exceeded." },
  { code: "P6010", message: "Project disabled." },

  { code: "P5011", message: "Too many requests." }
];